#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(pidof -o %PPID python /usr/sbin/i8kmonitor)
case "$1" in
  start)
    stat_busy "Starting i8kmonitor"
    [ -z "$PID" ] && /usr/sbin/i8kmonitor >/dev/null 2>&1 &
    PID=$(pidof -o %PPID python /usr/sbin/i8kmonitor)
    if [ -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      add_daemon i8kmonitor
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping i8kmonitor"
    [ ! -z "$PID" ]  && kill -USR1 $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon i8kmonitor
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
